# -- Provide a name in place of c8 for `app:` labels
nameOverride: ""
# -- Provide a name to substitute for the full names of resources
fullnameOverride: ""
# -- Labels to apply to all resources
commonLabels: {}

frontend:
  enabled: true

  # -- Configuration for frontend service
  service:
    type: ClusterIP
    port: "8080"

  image:
    repository: "ghcr.io/configure8inc/c8-frontend"
    pullPolicy: IfNotPresent
    tag: "1.0.0"

  replicaCount: 1

  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  # -- Define resources requests and limits for Pods. https://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # limits:
  #   cpu: 300m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  livenessProbe:
    httpGet:
      path: /
      port: 8080
    failureThreshold: 2
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /
      port: 8080
    failureThreshold: 2
    periodSeconds: 10
    initialDelaySeconds: 20

  podAnnotations: {}
  podSecurityContext:
    runAsUser: 101
    runAsGroup: 101
    fsGroup: 101
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "c8-frontend"

  podDisruptionBudget:
    # Specifies whether pod disruption budget should be created
    enabled: false
    # Number or percentage of pods that must be available
    minAvailable: 50%

common:
  revisionHistoryLimit: 3
  ttlSecondsAfterFinished: 172800

  ingress:
    # -- Enable ingress object for external access to the resources . Do not forget to add common.ingress.ingressClassName=""
    enabled: true
    ingressClassName: ""
    annotations: {}
    labels: {}
    pathType: Prefix

  # -- image pull secrets
  IMAGE_PULL_SECRET: c8-docker-registry-secret
  C8_SECRET_NAME: c8-secret

migration:
  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  image:
    repository: "ghcr.io/configure8inc/c8-migrations"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.0"

  podSecurityContext:
    runAsUser: 1051
    runAsGroup: 1051
    fsGroup: 1051
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

backend:
  enabled: true

  replicaCount: 1

  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  image:
    repository: "ghcr.io/configure8inc/c8-backend"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.0"

  # -- Configuration for backend service
  service:
    type: ClusterIP
    port: "5000"

  # -- Define resources requests and limits for Pods. https://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  livenessProbe:
    httpGet:
      path: /api/v1/ping
      port: 5000
    timeoutSeconds: 10
    failureThreshold: 3
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /api/v1/ping
      port: 5000
    timeoutSeconds: 10
    failureThreshold: 3
    periodSeconds: 10

  startupProbe:
    httpGet:
      path: /api/v1/ping
      port: 5000
    timeoutSeconds: 10
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 20

  podAnnotations: {}
  podSecurityContext:
    runAsUser: 1051
    runAsGroup: 1051
    fsGroup: 1051
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: "c8-backend"

  podDisruptionBudget:
    # -- Specifies whether pod disruption budget should be created
    enabled: false
    # -- Number or percentage of pods that must be available
    minAvailable: 50%

djm:
  enabled: true

  replicaCount: 1

  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  image:
    # -- c8 docker image repository
    repository: "ghcr.io/configure8inc/c8-djm"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.0"

  # -- Discovery job worker image
  DJW_IMAGE: "ghcr.io/configure8inc/c8-djw:1.0.0"

  # -- Discovery job worker NodeSelector key
  DJW_NODE_SELECTOR_KEY: ""
  # -- Discovery job worker NodeSelector value
  DJW_NODE_SELECTOR_VALUE: ""
  # -- Discovery job worker pod security context
  DJW_POD_SECURITY_CONTEXT: '{"runAsUser": 1052, "runAsGroup": 1052, "runAsNonRoot": true}'

  container:
    port: "5000"

  # -- Define resources requests and limits for Pods. https://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  podAnnotations: {}
  podSecurityContext:
    runAsUser: 1052
    runAsGroup: 1052
    fsGroup: 1052
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: "c8-djm"

    job_worker:
      # -- Specifies whether a service account should be created
      create: true
      # -- The name of the djw service account to use. If not set and create is true, a name is generated using the fullname template
      name: "c8-djw"
      # -- Annotations to add to the service account
      annotations: {}

ssa:
  enabled: true

  replicaCount: 1

  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  ingress:
    enabled: true
    ingressClassName: ""
    annotations: {}
    labels: {}
    pathType: Prefix

  image:
    repository: "ghcr.io/configure8inc/c8-ssa"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.0"

  container:
    port: "5000"

  # -- Configuration for ssa service
  service:
    enabled: true
    type: ClusterIP
    port: "5000"

  # -- Define resources requests and limits for Pods. https://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  livenessProbe:
    httpGet:
      path: /self-service/api/health
      port: 5000
      scheme: HTTP
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /self-service/api/health
      port: 5000
      scheme: HTTP
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 10

  podAnnotations: {}
  podSecurityContext:
    runAsUser: 1055
    runAsGroup: 1055
    fsGroup: 1055
    runAsNonRoot: true
  # fsGroup: 2000

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: "c8-ssa"

  podDisruptionBudget:
    # -- Specifies whether pod disruption budget should be created
    enabled: false
    # -- Number or percentage of pods that must be available
    minAvailable: 50%

pns:
  enabled: true

  replicaCount: 1

  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  image:
    repository: "ghcr.io/configure8inc/c8-pns"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.0.0"

  container:
    port: "5000"

  # -- Configuration for pns service
  service:
    enabled: true
    type: ClusterIP
    port: "5000"

  # -- Define resources requests and limits for Pods. https://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  podAnnotations: {}
  podSecurityContext:
    runAsUser: 1057
    runAsGroup: 1057
    fsGroup: 1057
    runAsNonRoot: true
  # fsGroup: 2000

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: "c8-pns"

  podDisruptionBudget:
    # Specifies whether pod disruption budget should be created
    enabled: false
    # Number or percentage of pods that must be available
    minAvailable: 50%

variables:
  ##### C8 #########
  # -- The region what actually we use with AWS integration
  AWS_REGION: "us-east-1"
  # -- Url on which the application will be available. For example https://configure8.my-company.io
  DEEPLINK_URL: ""
  # -- Url on which the application will be available. Usually should be the same as DEEPLINK_URLFor example https://configure8.my-company.io
  HOOKS_CALLBACK_URL: ""
  # -- Application analytics segment key
  SEGMENT_KEY: "na"
  # -- Enable or disable swagger documentation
  SWAGGER_ENABLED: "false"

  ##### SSA #########
  # -- Enable or disable swagger documentation
  SSA_SWAGGER_ENABLED: "false"

  ##### NPS #########
  # -- Default email for sending notifications.
  DEFAULT_SENDER: "notifications@example.com"
  # -- Flag to use SMTP for emails
  USE_SMTP_STRATEGY: "true"
  # -- Address of the SMTP server (e.g., SendGrid's server).
  SMTP_HOST: "smtp.sendgrid.net"
  # -- Port for connecting to the SMTP server
  SMTP_PORT: "587"

  ##### COMMON #########
  # -- Application timezone
  TZ: "America/New_York"
  # -- RabbitMQ host
  RABBITMQ_HOST: ""
  # -- RabbitMQ port
  RABBITMQ_PORT: 5672
  # -- The mechanism of how to authenticate with the database. Might be SCRAM-SHA-1 or any other supported by mongodb
  DB_AUTH_MECHANISM: "SCRAM-SHA-1"
  # -- Database host
  DB_HOST: ""
  # -- Database name
  DB_DATABASE: "c8"
  # -- Database port
  DB_PORT: "27017"
  # -- Type of the driver. For atlas mongoDbAtlas and mongoDb for the regular instance
  MONGO_DRIVER_TYPE: "mongoDb"
  # -- ElasticSearch url
  OPENSEARCH_NODE: ""
  # -- Snowflake account name
  SF_ACCOUNT: "c8-qa"
  # -- Snowflake db name
  SF_DATABASE: "C8"
  # -- Snowflake db schema
  SF_SCHEMA: "PUBLIC"
  # -- Snowflake warehouse name
  SF_WAREHOUSE: "DEV_WAREHOUSE"
  # -- Snowflake poolsize
  SF_POOLSIZE: "5"
  # -- Online analytical processing DB type
  OLAP_DB: "snowflake"
