# -- Provide a name in place of c8 for `app:` labels
nameOverride: ""
# -- Provide a name to substitute for the full names of resources
fullnameOverride: ""
# -- Labels to apply to all resources
commonLabels: {}

frontend:
  enabled: true

  # -- Frontend labels
  labels:
    appComponent: frontend

  # -- Configuration for frontend service
  service:
    type: ClusterIP
    port: "8080"

  image:
    repository: "ghcr.io/configure8inc/c8-frontend"
    pullPolicy: IfNotPresent

  replicaCount: 1

  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas:
    maxReplicas:
    targetCPUUtilizationPercentage:
    targetMemoryUtilizationPercentage:

  # -- Define resources requests and limits for Pods. https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 1
      memory: 256Mi
    requests:
      cpu: 0.2
      memory: 256Mi

  livenessProbe:
    httpGet:
      path: /
      port: 8080
    failureThreshold: 2
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /
      port: 8080
    failureThreshold: 2
    periodSeconds: 10
    initialDelaySeconds: 20

  podAnnotations: {}
  podSecurityContext:
    runAsUser: 101
    runAsGroup: 101
    fsGroup: 101
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "c8-frontend"

  podDisruptionBudget:
    # Specifies whether pod disruption budget should be created
    enabled: false
    # Number or percentage of pods that must be available
    minAvailable: 50%

common:
  revisionHistoryLimit: 3
  ttlSecondsAfterFinished: 172800

  ingress:
    # -- Enable ingress object for external access to the resources . Do not forget to add common.ingress.ingressClassName=""
    enabled: true
    ingressClassName: ""
    annotations: {}
    labels: {}
    pathType: Prefix
    additionalHosts: []

  # -- Application version (used for deployment and image tags)
  app_version: "2.120.0"

  # -- image pull secrets
  IMAGE_PULL_SECRET: c8-docker-registry-secret
  C8_SECRET_NAME: c8-secret

migration:
  enabled: true
  
  # -- Migration labels
  labels:
    appComponent: migration

  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  image:
    repository: "ghcr.io/configure8inc/c8-migrations"
    pullPolicy: IfNotPresent

  podSecurityContext:
    runAsUser: 1051
    runAsGroup: 1051
    fsGroup: 1051
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

backend:
  enabled: true

  # -- Backend labels
  labels:
    appComponent: backend

  replicaCount: 1

  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  autoscaling:
    enabled: false
    minReplicas:
    maxReplicas:
    targetCPUUtilizationPercentage:
    targetMemoryUtilizationPercentage:
  image:
    repository: "ghcr.io/configure8inc/c8-backend"
    pullPolicy: IfNotPresent

  # -- Configuration for backend service
  service:
    type: ClusterIP
    port: "5000"

  # -- Define resources requests and limits for Pods. https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 2Gi

  livenessProbe:
    httpGet:
      path: /api/v1/ping
      port: 5000
    timeoutSeconds: 10
    failureThreshold: 3
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /api/v1/ping
      port: 5000
    timeoutSeconds: 10
    failureThreshold: 3
    periodSeconds: 10

  startupProbe:
    httpGet:
      path: /api/v1/ping
      port: 5000
    timeoutSeconds: 10
    failureThreshold: 5
    periodSeconds: 10
    initialDelaySeconds: 20

  podAnnotations: {}
  podSecurityContext:
    runAsUser: 1051
    runAsGroup: 1051
    fsGroup: 1051
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: "c8-backend"

  podDisruptionBudget:
    # -- Specifies whether pod disruption budget should be created
    enabled: false
    # -- Number or percentage of pods that must be available
    minAvailable: 50%

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  # --- Persistence ---
  persistence:
    # -- Persistence type
    type: pvc
    # -- Enable persistence using Persistent Volume Claims
    enabled: false
    # -- Storage class name
    storageClassName: efs-sc
    # -- Access mode
    accessModes:
      - ReadWriteOne
    # -- Storage size
    size: 10Gi
    # -- PVC annotations
    annotations: {}
    # -- PVC finalizers
    finalizers:
      - kubernetes.io/pvc-protection
    # -- PVC selector labels
    selectorLabels: {}
    # -- PVC extra PVC labels
    extraPvcLabels: {}
    # -- Use an existing PVC? If yes, set this to the name of the PVC
    existingClaim: ""
    # -- Mount path
    mountPath: /home/c8/app/packages/backend

djm:
  enabled: true

  # -- Backend labels
  labels:
    appComponent: djm

  replicaCount: 1

  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  image:
    # -- c8 docker image repository
    repository: "ghcr.io/configure8inc/c8-djm"
    pullPolicy: IfNotPresent

  # -- Discovery job worker image
  DJW_IMAGE_REPO: "ghcr.io/configure8inc/c8-djw"

  # -- Discovery job worker NodeSelector key
  DJW_NODE_SELECTOR_KEY: ""
  # -- Discovery job worker NodeSelector value
  DJW_NODE_SELECTOR_VALUE: ""
  # -- Discovery job worker pod security context
  DJW_POD_SECURITY_CONTEXT: '{"runAsUser": 1053, "runAsGroup": 1053, "runAsNonRoot": true}'

  container:
    port: "5000"

  # -- Define resources requests and limits for Pods. https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http
  podAnnotations: {}
  podSecurityContext:
    runAsUser: 1052
    runAsGroup: 1052
    fsGroup: 1052
    runAsNonRoot: true

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: "c8-djm"

    job_worker:
      # -- Specifies whether a service account should be created
      create: true
      # -- The name of the djw service account to use. If not set and create is true, a name is generated using the fullname template
      name: "c8-djw"
      # -- Annotations to add to the service account
      annotations: {}

ssa:
  enabled: true

  replicaCount: 1

  # -- Backend labels
  labels:
    appComponent: ssa

  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  image:
    repository: "ghcr.io/configure8inc/c8-ssa"
    pullPolicy: IfNotPresent

  container:
    port: "5000"

  # -- Configuration for ssa service
  service:
    enabled: true
    type: ClusterIP
    port: "5000"

  # -- Define resources requests and limits for Pods. https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi

  livenessProbe:
    httpGet:
      path: /self-service/api/health
      port: 5000
      scheme: HTTP
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /self-service/api/health
      port: 5000
      scheme: HTTP
    failureThreshold: 3
    timeoutSeconds: 10
    periodSeconds: 10

  podAnnotations: {}
  podSecurityContext:
    runAsUser: 1055
    runAsGroup: 1055
    fsGroup: 1055
    runAsNonRoot: true
  # fsGroup: 2000

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: "c8-ssa"

  podDisruptionBudget:
    # -- Specifies whether pod disruption budget should be created
    enabled: false
    # -- Number or percentage of pods that must be available
    minAvailable: 50%

pns:
  enabled: true

  # -- Backend labels
  labels:
    appComponent: pns

  replicaCount: 1

  # -- Node labels for pod assignment https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

  image:
    repository: "ghcr.io/configure8inc/c8-pns"
    pullPolicy: IfNotPresent

  container:
    port: "5000"

  # -- Configuration for pns service
  service:
    enabled: true
    type: ClusterIP
    port: "5000"

  # -- Define resources requests and limits for Pods. https://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

  # livenessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  # readinessProbe:
  #   httpGet:
  #     path: /
  #     port: http

  podAnnotations: {}
  podSecurityContext:
    runAsUser: 1057
    runAsGroup: 1057
    fsGroup: 1057
    runAsNonRoot: true
  # fsGroup: 2000

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
    name: "c8-pns"

  podDisruptionBudget:
    # Specifies whether pod disruption budget should be created
    enabled: false
    # Number or percentage of pods that must be available
    minAvailable: 50%

variables:
  ##### COMMON CONFIGMAP #########
  # -- Application env
  ENV: "prod"
  # -- Logging level
  LOGGING_LEVEL: "info"
  # -- Maintenance mode
  MAINTENANCE_MODE: "false"
  # -- Node environment
  NODE_ENV: "production"
  # -- Node port
  NODE_PORT: "5000"
  # -- Application stage
  STAGE: "prod"
  # -- Application version
  VERSION: "v1.0.0"
  # -- Allow to retry write operations in case of failure
  DB_WRITE_RETRIES: "true"
  # -- DB aurh source
  DB_AUTH_SOURCE: "c8"
  # -- Redis connect retries
  REDIS_CONNECT_RETRIES: "20"
  # -- Redis connect retry timeout
  REDIS_CONNECT_RETRY_TIMEOUT: "1000"

  ##### C8 #########
  # -- The region what actually we use with AWS integration
  AWS_REGION: "us-east-1"
  # -- Url on which the application will be available. For example https://configure8.my-company.io
  DEEPLINK_URL: ""
  # -- Enable or disable swagger documentation
  SWAGGER_ENABLED: "false"
  # -- Enable or disable analytics
  DISABLE_ANALYTICS: "true"

  ##### SSA #########
  # -- Enable or disable swagger documentation
  SSA_SWAGGER_ENABLED: "false"
  # -- Enable or disable AWS authentication
  OPENSEARCH_AWS_AUTHENTICATE: "true"
  # -- Specify the AWS OpenSearch service type, either 'es' for OpenSearch or 'aoss' for serverless OpenSearch Service
  OPENSEARCH_AWS_SERVICE: "es"

  ##### NPS #########
  # -- Default email for sending notifications.
  DEFAULT_SENDER: ""
  # -- Flag to use SMTP for emails
  USE_SMTP_STRATEGY: "true"
  # -- Address of the SMTP server (e.g., SendGrid's server).
  SMTP_HOST: "smtp.sendgrid.net"
  # -- Port for connecting to the SMTP server
  SMTP_PORT: "587"

  ##### COMMON #########
  # -- Application timezone
  TZ: "America/New_York"
  # -- RabbitMQ host
  RABBITMQ_HOST: ""
  # -- RabbitMQ port
  RABBITMQ_PORT: 5672
  # -- RabbitMQ ssl flag
  RABBITMQ_USE_SSL: "false"
  # -- The mechanism of how to authenticate with the database. Might be SCRAM-SHA-1 or any other supported by mongodb
  DB_AUTH_MECHANISM: "SCRAM-SHA-1"
  # -- Database host
  DB_HOST: ""
  # -- Database name
  DB_DATABASE: "c8"
  # -- Database port
  DB_PORT: "27017"
  # -- Additional parameters for the database connection, should be provided int query params format like "key1=value&key2=value2". If no params provided should be empty string.
  DB_CONNECTION_ADDITIONAL_PARAMS: ""
  # -- Type of the driver. For atlas mongoDbAtlas and mongoDb for the regular instance
  MONGO_DRIVER_TYPE: "mongoDb"
  # -- ElasticSearch url
  OPENSEARCH_NODE: ""
  # -- Snowflake account name
  SF_ACCOUNT: ""
  # -- Snowflake db name
  SF_DATABASE: "C8"
  # -- Snowflake db schema
  SF_SCHEMA: "PUBLIC"
  # -- Snowflake RO warehouse name
  SF_READ_WAREHOUSE: ""
  # -- Snowflake RW warehouse name
  SF_WRITE_WAREHOUSE: ""
  # -- Snowflake Discovery warehouse name
  SF_DISCOVERY_WRITE_WAREHOUSE: ""
  # -- Snowflake poolsize
  SF_POOLSIZE: "5"
  # -- Online analytical processing DB type
  OLAP_DB: "snowflake"
  # -- Enable or disable redis cache
  REDIS_ENABLED: "true"
  # -- Redis host
  REDIS_HOST: ""
  # -- Redis port
  REDIS_PORT: "6379"
  # -- Redis cache ttl
  REDIS_CACHE_TTL: "3600"
  # -- Redis connect timeout
  REDIS_CONNECT_TIMEOUT: "5000"
  # -- GitHub custom rate limit
  GITHUB_CUSTOM_RATE_LIMIT: ""
  # -- Throttling enable or disable
  THROTTLE_ENABLED: "true"
  # -- Throttling ttl
  THROTTLE_TTL: "60000"
   # -- Throttling limit
  THROTTLE_LIMIT: "10"



# External secrets manager configuration: currently supported AWS Secrets Manager and AWS Parameter Store. To use it, the External Secrets Operator should be installed!
# https://external-secrets.io/latest/introduction/overview/
# https://external-secrets.io/latest/introduction/getting-started/#installing-with-helm
aws_secrets_manager:
  # -- Enable or disable AWS Secrets Manager
  enabled: false
  # -- The interval at which the secret is refreshed
  refreshInterval: 24h
  # -- The kube secret name that will be created
  secret_name: c8-secret

aws_parameter_store:
  # -- Enable or disable AWS Parameter Store
  enabled: false
  # -- The interval at which the secret is refreshed
  refreshInterval: 24h
  # -- The kube secret name that will be created
  secret_name: c8-secret