apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "c8.fullname" . }}-backend-params
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded"
data:
  # -- Used to define the relative path to the backend API, by default should be /api.v1
  API_PREFIX: "/api/v1"
  # -- Description for the swagger file, usually shouldn't be changed
  SWAGGER_DESCRIPTION: "C8 API"
  # -- Swagger documentation relative url, by default /docs
  SWAGGER_PREFIX: "/docs"
  # -- Swagger documentation title
  SWAGGER_TITLE: "C8 Backend API"