{{- if and .Values.backend.persistence.enabled (not .Values.backend.persistence.existingClaim) (eq .Values.backend.persistence.type "pvc")}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "c8.fullname" . }}-pvc
  labels:
    {{- include "c8.labels" . | nindent 4 }}
    {{- with .Values.backend.persistence.extraPvcLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.backend.persistence.annotations  }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.backend.persistence.finalizers  }}
  finalizers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.backend.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size | quote }}
  {{- with .Values.backend.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.backend.persistence.selectorLabels }}
  selector:
    matchLabels:
    {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}