apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "c8.fullname" . }}-common-params
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded"
data:
  DB_WRITE_RETRIES: "true"
  ENV: "prod"
  LOGGING_LEVEL: "info"
  MAINTENANCE_MODE: "false"
  NODE_ENV: "production"
  NODE_PORT: "5000"
  STAGE: "prod"
  VERSION: "v1.0.0"