apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "c8.fullname" . }}-params
data:
  DB_WRITE_RETRIES: "true"
  ENV: "prod"
  LOGGING_LEVEL: "info"
  MAINTENANCE_MODE: "false"
  NODE_ENV: "production"
  NODE_PORT: "5000"
  STAGE: "prod"
  SSA_TIMEOUT: "10000"