apiVersion: v1
kind: Service
metadata:
  name: {{ include "c8.fullname" . }}-crep
  labels:
    {{- include "c8.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.crep.service.type }}
  ports:
    - port: {{ .Values.crep.service.port }}
      targetPort: {{ .Values.crep.service.port }}
      protocol: TCP
      name: http
  selector:
    c8app: "crep"
