{{- if .Values.crep.enabled }}
{{- if .Values.crep.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "c8.fullname" . }}-crep
  labels:
    {{- include "c8.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "c8.fullname" . }}-crep
  minReplicas: {{ .Values.crep.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.crep.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.crep.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.crep.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.crep.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.crep.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}