apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "c8.fullname" . }}-crep-params
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded"
data:
  # -- Used to define the relative path to the backend API, by default should be /api.v1
  API_PREFIX: "/api/v1"