apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "c8.fullname" . }}-djm-params
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded"
data:
  # -- Required for the health checks, should be by default /api/v1
  API_PREFIX: "/api/v1"
  # -- Workers container names
  DISCOVERY_CONTAINER_NAME: "c8-discovery-job-worker"
  # -- Storing diff information for the resources when something been changed
  DJW_TRACK_ENTITY_LINEAGE: "true"
  # -- Maximum hours for the job execution
  JOB_DEAD_TIMEOUT_HOURS: "3"
  # -- list of the jobs that are going to be executed by discovery manager
  JOB_TYPES: "DISCOVERY, DISCOVERY_ON_DEMAND, AUTOMAPPING_BY_TAGS, COSTS_RECALCULATE, SCORECARD_AGGREGATION, SCORECARD_AGGREGATION_ON_DEMAND, SSA_TERMINATION, CALCULATE_SERVICE_DETAILS, SCORECARD_NOTIFICATION, SERVICE_NOTIFICATION, CREDENTIALS_NOTIFICATION"
  # -- Determines the time when the schedule should be checked in MS
  LOOP_SLEEP_TIME: "10000"
  # -- Maximum simultaneously executed jobs
  MAX_JOB_LIMIT: "10"
  # -- For the production should be true, should be used only by qualified C8 developers
  USE_K8: "true"