{{- if .Values.djm.enabled }}
{{- if .Values.djm.serviceAccount.job_worker.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "c8.serviceAccountNameDjw" . }}
  labels:
    {{- include "c8.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.djm.serviceAccount.job_worker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
