{{- if .Values.frontend.enabled }}
{{- if .Values.frontend.ingress.enabled -}}
{{- $ingressApiIsStable := eq (include "c8.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "c8.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "c8.ingress.supportsPathType" .) "true" -}}
{{- $fullName := include "c8.fullname" . -}}
{{- $servicePort := .Values.frontend.service.port -}}
{{- $ingressPath := .Values.frontend.ingress.path -}}
{{- $ingressPathType := .Values.frontend.ingress.pathType -}}
apiVersion: {{ include "c8.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}-frontend
  labels:
    {{- include "c8.labels" . | nindent 4 }}
    {{- with .Values.frontend.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.frontend.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.common.ingress.ingressClassName  }}
  ingressClassName: {{ .Values.common.ingress.ingressClassName }}
  {{- end -}}
  {{- with .Values.frontend.ingress.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.variables.DEEPLINK_URL | replace "https://" "" }}
      http:
        paths:
          - path: /
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}-frontend
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}-frontend
              servicePort: {{ $servicePort }}
              {{- end }}
{{- end }}
{{- end }}
