{{- if .Values.pns.enabled }}
{{- if .Values.pns.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "c8.fullname" . }}-pns-pdb
spec:
  minAvailable: "{{ default "50%" .Values.pns.podDisruptionBudget.minAvailable }}"
  selector:
    matchLabels:
      c8app: "pns"
{{- end }}
{{- end }}
