apiVersion: v1
kind: Service
metadata:
  name: {{ include "c8.fullname" . }}-backend
  labels:
    {{- include "c8.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.backendService.type }}
  ports:
    - port: {{ .Values.backendService.port }}
      targetPort: {{ .Values.backendService.port }}
      protocol: TCP
      name: http
  selector:
    c8app: "backend"
