{{- if .Values.ssa.enabled }}
{{- if .Values.ssa.ingress.enabled -}}
{{- if .Values.ssa.service.enabled -}}
{{- $ingressApiIsStable := eq (include "c8.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "c8.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "c8.ingress.supportsPathType" .) "true" -}}
{{- $fullName := include "c8.fullname" . -}}
{{- $servicePort := .Values.ssa.service.port -}}
{{- $ingressPath := .Values.ssa.ingress.path -}}
{{- $ingressPathType := .Values.ssa.ingress.pathType -}}
apiVersion: {{ include "c8.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ssa
  labels:
    {{- include "c8.labels" . | nindent 4 }}
    {{- with .Values.ssa.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ssa.ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ssa.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ssa.ingress.ingressClassName }}
  {{- end -}}
  {{- with .Values.ssa.ingress.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.variables.DEEPLINK_URL | replace "https://" "" }}
      http:
        paths:
          - path: /self-service/api
            {{- if $ingressSupportsPathType }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}-ssa
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $fullName }}-ssa
              servicePort: {{ $servicePort }}
              {{- end }}
{{- end }}
{{- end }}
{{- end }}
