apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "c8.fullname" . }}-ssa-params
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded"
data:
  # -- Used to define the relative path to the backend API, for production should be with default value
  API_PREFIX: "/self-service/api" 
  # -- Description for the swagger file, usually shouldn't be changed
  SWAGGER_DESCRIPTION: "Self Service API documentation"
  # -- Swagger documentation relative url, by default /self-service/api/docs
  SSA_SWAGGER_PREFIX: "/self-service/api/docs"
  # -- Swagger documentation title
  SSA_SWAGGER_TITLE: "C8 Self-Service API"