name: 'Package charts'

on:
  workflow_dispatch: 
  pull_request:
    branches: [main, production]
    types: [opened]


env:
  HELM_VERSION    : "v3.12.0"


jobs:
  build:
    name: Package
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.issue.pull_request.head.ref }} # Checkout the PR branch
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Install Helm
      uses: ./.github/actions/install-helm
      with:
        helm_version: ${{ env.HELM_VERSION }}

    - name: Package helm charts
      run: |
        helm package ./helm-charts/c8 -d ./store
        helm repo index --url https://helm.configure8.io/store/ --merge index.yaml ./store

    - name: Commit changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Package charts" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}