name: 'Package charts'

on:
  workflow_dispatch: 
  pull_request:
    branches: [main, production]
    types: [opened]


env:
  HELM_VERSION    : "v3.12.0"


jobs:
  build:
    name: Package
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.issue.pull_request.head.ref }} # Checkout the PR branch
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Install Helm
      uses: ./.github/actions/install-helm
      with:
        helm_version: ${{ env.HELM_VERSION }}

    - name: Package helm charts
      run: |
        helm package ./helm-charts/c8 -d ./store
        helm repo index --url https://helm.configure8.io/store/ --merge index.yaml ./store

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add ./store/*
        git commit -m "Package charts" || echo "No changes to commit"
        git push