name: 'Lint charts'

on:
  workflow_dispatch: 
  pull_request:
    branches: [main, production]
      
env:
  HELM_VERSION    : "v3.12.0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install Helm
      uses: ./.github/actions/install-kubectl-helm
      with:
        helm_version: ${{ env.HELM_VERSION }}

    - name: Lint helm charts
      run: |
        helm lint helm-charts/*

